### ISSUE TITLE
required bot10v3.ui file

### ISSUE THREAD

**Issue by iconsis** [AlessanderSalgado/BotIqOption#1]
Traceback (most recent call last):
  File "e:\iqoption\BotIqOption-main\Bot10v4.py", line 62, in <module>
    bot10v2=uic.loadUi('fonttela\\bot10v3.ui')
  File "C:\Users\icons\AppData\Local\Programs\Python\Python310\lib\site-packages\PyQt5\uic\__init__.py", line 238, in loadUi    
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\Users\icons\AppData\Local\Programs\Python\Python310\lib\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "C:\Users\icons\AppData\Local\Programs\Python\Python310\lib\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
  File "C:\Users\icons\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\icons\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'fonttela\\bot10v3.ui'

**Comment by liberwicca** [comment]
bad proyect, incompleted... trash
